# Generated by Django 3.2 on 2025-01-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, default='sahilnyk', max_length=100),
        ),
    ]
