# Generated by Django 3.2 on 2025-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_auto_20250421_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogimage',
            name='blog',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='default_category', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='links',
            field=models.URLField(default='default_link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='default_author', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
