# Generated by Django 5.2 on 2025-04-25 22:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0007_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
