# Generated by Django 3.2 on 2025-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_auto_20250421_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tech_stack',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='live_link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='default_category', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.URLField(default='default_link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ProjectCategory',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
