# Generated by Django 3.2 on 2025-04-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0008_auto_20250425_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='techstack',
            field=models.CharField(max_length=200),
        ),
    ]
