# Generated by Django 5.2 on 2025-04-25 22:00

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0009_alter_project_techstack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
